function i = loadInterneuronData(d,m)

    i.mua = mua_at_date(m.today, m.mua_filelist_fn, 'keep_groups', m.keepGroups,...
    'trode_groups', m.trode_groups_fn, 'timewin', m.loadTimewin, 'arte_correction_factor',m.arteCorrectionFactor,...
    'ad_trodes',m.ad_tts,'arte_trodes',m.arte_tts,'width_window',m.width_window,'threshold',m.threshold, ...
    'segment_style', 'areas');
    [~,i.mua_rate] = assign_rate_by_time(d.mua,'timewin',m.loadTimewin,'samplerate',400,'gauss_sd_sec',0.04);    

end